
server:
  port: 6060

spring:
  datasource:
    url: jdbc:mysql://www.mysql.com/spvu?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

logging:
  level:
    com.czqx.ordinary: debug
mybatis:
  mapper-locations: /mappers/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true