
server:
  port: 6060
spring:
  datasource:
    url: jdbc:mysql://www.mysql.com/spvu?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    host: 192.168.222.136
    port: 6379
    password:
    database: 0
#  main:
#    web-application-type: none
logging:
  level:
    com.czqx: debug
mybatis:
  mapper-locations: /mappers/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
fdfs:
  urlPath: 192.168.222.136/
  so-timeout: 1500
  connect-timeout: 600
  thumb-image:
    height: 150
    width: 150
  tracker-list: 192.168.222.136:22122
